import type { Product, Review } from "./schema";

/**
 * Catálogo de demonstração. Fotos reais do Unsplash (licença Unsplash, uso comercial livre).
 * Preços em centavos.
 */

const SIZES = (stock: [number, number, number, number, number]) =>
  (["P", "M", "G", "GG", "XG"] as const).map((label, i) => ({ label, stock: stock[i] }));

export const PRODUCTS: Product[] = [
  {
    slug: "moletom-nebula-oversized",
    name: "Moletom Nebula Oversized",
    subtitle: "Moletom unissex",
    description:
      "Moletom de algodão peluciado 480 g/m², modelagem oversized e capuz forrado. Punhos e barra em ribana dupla para manter o caimento depois de muitas lavagens.",
    category: "moletons",
    gender: "unissex",
    priceCents: 28990,
    compareAtCents: null,
    images: [
      { unsplashId: "REOoETloFqE", alt: "Pessoa vestindo moletom preto com capuz", author: "Unsplash" },
      { unsplashId: "XEmkHQXAHFs", alt: "Homem de moletom preto agachado na rua", author: "Maria Fernanda Pissioli" },
    ],
    colors: [
      { name: "Preto", hex: "#111111" },
      { name: "Grafite", hex: "#4a4a4f" },
      { name: "Violeta", hex: "#6d3af5" },
    ],
    sizes: SIZES([6, 12, 4, 9, 0]),
    badge: "mais-vendido",
    rating: 4.9,
    reviewCount: 1284,
    soldLastWeek: 312,
    details: ["80% algodão, 20% poliéster", "Gramatura 480 g/m²", "Capuz forrado com cordão plano", "Bolso canguru", "Lavar do avesso em água fria"],
  },
  {
    slug: "calca-cargo-orbit",
    name: "Calça Cargo Orbit",
    subtitle: "Calça masculina",
    description:
      "Calça cargo em sarja pesada com seis bolsos, joelho articulado e barra com regulagem. Caimento reto, confortável para o dia inteiro.",
    category: "calcas",
    gender: "masculino",
    priceCents: 22990,
    compareAtCents: 29990,
    images: [{ unsplashId: "fjFYb31Qsis", alt: "Homem sorrindo usando calça cargo marrom", author: "Unsplash" }],
    colors: [
      { name: "Caramelo", hex: "#8a6a45" },
      { name: "Preto", hex: "#111111" },
    ],
    sizes: SIZES([3, 8, 10, 5, 2]),
    badge: null,
    rating: 4.8,
    reviewCount: 917,
    soldLastWeek: 204,
    details: ["100% algodão (sarja 12 oz)", "Seis bolsos", "Barra com cordão de regulagem", "Zíper YKK"],
  },
  {
    slug: "camiseta-pixel-heavy",
    name: "Camiseta Pixel Heavy",
    subtitle: "Camiseta unissex",
    description:
      "Camiseta de malha 260 g/m², gola canelada de 2,5 cm e ombro levemente caído. A malha grossa não fica transparente e mantém a forma.",
    category: "camisetas",
    gender: "unissex",
    priceCents: 13990,
    compareAtCents: null,
    images: [{ unsplashId: "WWesmHEgXDs", alt: "Homem vestindo camiseta branca de gola careca", author: "Anomaly" }],
    colors: [
      { name: "Branco", hex: "#fafafa" },
      { name: "Preto", hex: "#111111" },
      { name: "Areia", hex: "#d8c9a8" },
      { name: "Violeta", hex: "#6d3af5" },
    ],
    sizes: SIZES([2, 4, 3, 1, 0]),
    badge: "ultimas-unidades",
    rating: 4.7,
    reviewCount: 864,
    soldLastWeek: 458,
    details: ["100% algodão penteado", "Malha 260 g/m²", "Pré-encolhida", "Gola canelada 2,5 cm"],
  },
  {
    slug: "jaqueta-corta-vento-drift",
    name: "Jaqueta Corta-vento Drift",
    subtitle: "Jaqueta unissex",
    description:
      "Corta-vento em nylon ripstop com tratamento repelente à água, capuz embutido na gola e forro em tela para ventilar.",
    category: "jaquetas",
    gender: "unissex",
    priceCents: 34990,
    compareAtCents: null,
    images: [{ unsplashId: "hIv7JMBG6OY", alt: "Jaqueta corta-vento branca, azul e laranja", author: "Jay Skyler" }],
    colors: [
      { name: "Azul e laranja", hex: "#2c4a8a" },
      { name: "Preto", hex: "#111111" },
      { name: "Oliva", hex: "#5b6142" },
    ],
    sizes: SIZES([5, 9, 11, 6, 3]),
    badge: "novo",
    rating: 4.8,
    reviewCount: 142,
    soldLastWeek: 96,
    details: ["100% poliamida ripstop", "Repelente à água", "Capuz embutido na gola", "Forro em tela"],
  },
  {
    slug: "moletom-ziper-shadow",
    name: "Moletom Zíper Shadow",
    subtitle: "Moletom masculino",
    description:
      "Moletom com zíper frontal inteiro, capuz duplo e bolsos laterais com forro. Peso médio, ideal para usar aberto por cima da camiseta.",
    category: "moletons",
    gender: "masculino",
    priceCents: 30990,
    compareAtCents: null,
    images: [{ unsplashId: "Jn0jgkuXKY8", alt: "Pessoa vestindo moletom preto com zíper", author: "Spencer Davis" }],
    colors: [
      { name: "Preto", hex: "#111111" },
      { name: "Mescla", hex: "#9a9a9e" },
    ],
    sizes: SIZES([4, 7, 9, 4, 2]),
    badge: null,
    rating: 4.6,
    reviewCount: 388,
    soldLastWeek: 71,
    details: ["80% algodão, 20% poliéster", "Gramatura 420 g/m²", "Zíper de metal", "Capuz duplo"],
  },
  {
    slug: "moletom-dusk",
    name: "Moletom Dusk",
    subtitle: "Moletom feminino",
    description:
      "Moletom feminino com capuz amplo e comprimento na altura do quadril. Interior peluciado e toque macio.",
    category: "moletons",
    gender: "feminino",
    priceCents: 26990,
    compareAtCents: null,
    images: [{ unsplashId: "tE_aGqG80G0", alt: "Mulher vestindo moletom preto com capuz", author: "Spencer Davis" }],
    colors: [
      { name: "Preto", hex: "#111111" },
      { name: "Lilás", hex: "#b9a6e8" },
    ],
    sizes: SIZES([7, 10, 6, 3, 1]),
    badge: "novo",
    rating: 4.9,
    reviewCount: 211,
    soldLastWeek: 133,
    details: ["80% algodão, 20% poliéster", "Interior peluciado", "Capuz amplo"],
  },
  {
    slug: "calca-cargo-solar",
    name: "Calça Cargo Solar",
    subtitle: "Calça feminina",
    description:
      "Calça cargo feminina de cintura alta, perna ampla e bolsos laterais com lapela. Sarja leve para usar o ano todo.",
    category: "calcas",
    gender: "feminino",
    priceCents: 23990,
    compareAtCents: null,
    images: [
      { unsplashId: "5WzXaxO74NE", alt: "Mulher de moletom cinza e calça cargo amarela", author: "Collins Lesulie" },
    ],
    colors: [
      { name: "Amarelo", hex: "#e2b33c" },
      { name: "Preto", hex: "#111111" },
    ],
    sizes: SIZES([6, 9, 7, 2, 0]),
    badge: "mais-vendido",
    rating: 4.8,
    reviewCount: 502,
    soldLastWeek: 187,
    details: ["98% algodão, 2% elastano", "Cintura alta", "Perna ampla", "Bolsos com lapela"],
  },
  {
    slug: "moletom-haze",
    name: "Moletom Haze",
    subtitle: "Moletom feminino",
    description: "Moletom de capuz com ombro caído e manga longa com punho alto. Cor única, lavagem suave.",
    category: "moletons",
    gender: "feminino",
    priceCents: 25990,
    compareAtCents: null,
    images: [{ unsplashId: "YBHmeoDzS0U", alt: "Mulher de moletom com capuz em retrato", author: "Unsplash" }],
    colors: [{ name: "Cinza", hex: "#b3b3b3" }],
    sizes: SIZES([4, 8, 5, 2, 1]),
    badge: null,
    rating: 4.7,
    reviewCount: 176,
    soldLastWeek: 58,
    details: ["80% algodão, 20% poliéster", "Ombro caído", "Punho alto em ribana"],
  },
  {
    slug: "moletom-ziper-fog",
    name: "Moletom Zíper Fog",
    subtitle: "Moletom feminino",
    description: "Moletom com zíper e modelagem ajustada, perfeito com calça de moletom ou cargo.",
    category: "moletons",
    gender: "feminino",
    priceCents: 27990,
    compareAtCents: 34990,
    images: [
      { unsplashId: "1d70_Akjfsc", alt: "Mulher de moletom cinza com zíper e calça preta", author: "Unsplash" },
    ],
    colors: [{ name: "Cinza", hex: "#a7a7ab" }],
    sizes: SIZES([3, 5, 4, 1, 0]),
    badge: null,
    rating: 4.6,
    reviewCount: 93,
    soldLastWeek: 41,
    details: ["80% algodão, 20% poliéster", "Zíper frontal", "Modelagem ajustada"],
  },
  {
    slug: "camiseta-core",
    name: "Camiseta Core",
    subtitle: "Camiseta masculina",
    description: "A básica que vai com tudo: malha 200 g/m², gola reforçada e modelagem regular.",
    category: "camisetas",
    gender: "masculino",
    priceCents: 9990,
    compareAtCents: null,
    images: [{ unsplashId: "LK4lk66tAbk", alt: "Homem vestindo camiseta branca ao ar livre", author: "Brian Lundquist" }],
    colors: [
      { name: "Branco", hex: "#fafafa" },
      { name: "Preto", hex: "#111111" },
      { name: "Marinho", hex: "#1f2a44" },
    ],
    sizes: SIZES([10, 14, 12, 8, 4]),
    badge: null,
    rating: 4.7,
    reviewCount: 1530,
    soldLastWeek: 620,
    details: ["100% algodão", "Malha 200 g/m²", "Modelagem regular"],
  },
  {
    slug: "camiseta-essential",
    name: "Camiseta Essential",
    subtitle: "Camiseta masculina",
    description: "Camiseta de algodão pima com toque sedoso e costura dupla na barra.",
    category: "camisetas",
    gender: "masculino",
    priceCents: 10990,
    compareAtCents: 14990,
    images: [{ unsplashId: "x6sryLt6VZ0", alt: "Homem de camiseta branca em fundo cinza", author: "Unsplash" }],
    colors: [{ name: "Branco", hex: "#fafafa" }],
    sizes: SIZES([2, 6, 5, 3, 1]),
    badge: null,
    rating: 4.5,
    reviewCount: 244,
    soldLastWeek: 88,
    details: ["100% algodão pima", "Costura dupla", "Pré-encolhida"],
  },
  {
    slug: "jaqueta-glass",
    name: "Jaqueta Corta-vento Glass",
    subtitle: "Jaqueta masculina",
    description: "Corta-vento translúcida em TPU leve, com capuz e ajuste na barra. Para chamar atenção em dia de chuva.",
    category: "jaquetas",
    gender: "masculino",
    priceCents: 37990,
    compareAtCents: null,
    images: [{ unsplashId: "u-FOgI41dGQ", alt: "Homem vestindo jaqueta corta-vento transparente", author: "David Beneš" }],
    colors: [{ name: "Transparente", hex: "#e8eef2" }],
    sizes: SIZES([2, 4, 5, 3, 1]),
    badge: "novo",
    rating: 4.6,
    reviewCount: 64,
    soldLastWeek: 37,
    details: ["100% TPU", "Impermeável", "Capuz com regulagem"],
  },
  {
    slug: "jaqueta-urban",
    name: "Jaqueta Urban",
    subtitle: "Jaqueta feminina",
    description: "Jaqueta de sarja com gola alta e bolsos embutidos. Leve o bastante para o meio da estação.",
    category: "jaquetas",
    gender: "feminino",
    priceCents: 32990,
    compareAtCents: null,
    images: [{ unsplashId: "6CO4SA0ySg8", alt: "Mulher caminhando na rua de jaqueta", author: "Jonathan Sanchez" }],
    colors: [
      { name: "Preto", hex: "#111111" },
      { name: "Cáqui", hex: "#a39170" },
    ],
    sizes: SIZES([4, 6, 5, 2, 1]),
    badge: null,
    rating: 4.7,
    reviewCount: 129,
    soldLastWeek: 52,
    details: ["100% algodão", "Gola alta", "Bolsos embutidos"],
  },
];

const REVIEW_TEMPLATES: Omit<Review, "id" | "productSlug">[] = [
  {
    author: "Larissa Okamoto",
    city: "São Paulo, SP",
    rating: 5,
    title: "Caimento perfeito",
    body: "Tecido pesado do jeito certo e a modelagem ficou exatamente como nas fotos. Chegou em 3 dias.",
    sizeBought: "M",
    createdAt: "2026-09-12",
  },
  {
    author: "Thiago Brandão",
    city: "Recife, PE",
    rating: 5,
    title: "Vale cada centavo",
    body: "Já lavei várias vezes e não perdeu a forma nem a cor. Vou comprar em outra cor.",
    sizeBought: "G",
    createdAt: "2026-08-29",
  },
  {
    author: "Beatriz Nunes",
    city: "Belo Horizonte, MG",
    rating: 4,
    title: "Muito bom, veste grande",
    body: "Qualidade excelente. A modelagem é mais larga, se quiser mais ajustado vale pegar um tamanho abaixo.",
    sizeBought: "P",
    createdAt: "2026-08-17",
  },
];

export const REVIEWS: Review[] = PRODUCTS.flatMap((p) =>
  REVIEW_TEMPLATES.map((r, i) => ({ ...r, id: `${p.slug}-${i}`, productSlug: p.slug })),
);

/** Fotos editoriais da home. */
export const EDITORIAL = {
  hero: { unsplashId: "XEmkHQXAHFs", alt: "Homem de moletom preto agachado na rua", author: "Maria Fernanda Pissioli" },
  colecao: { unsplashId: "XBqzXZZiaO4", alt: "Dois homens posando com roupas streetwear", author: "Dwayne Joe" },
  feminino: { unsplashId: "5WzXaxO74NE", alt: "Mulher de moletom cinza e calça cargo amarela", author: "Collins Lesulie" },
  look: { unsplashId: "vEoNuyoy9cw", alt: "Mulher vestindo moletom preto", author: "Unsplash" },
  drops: { unsplashId: "MgQKkfo8fp0", alt: "Vitrine de loja de roupas com manequins", author: "QingYu" },
  cupom: { unsplashId: "Owv9aPPY_ns", alt: "Mulher segurando sacolas de compras", author: "Vitaly Gariev" },
  frete: { unsplashId: "2E0EKnDpHso", alt: "Homem atravessando a rua com sacolas de compras", author: "Unsplash" },
} as const;

export const CATEGORY_COVERS = {
  moletons: { unsplashId: "tE_aGqG80G0", alt: "Mulher vestindo moletom preto com capuz", author: "Spencer Davis" },
  camisetas: { unsplashId: "LK4lk66tAbk", alt: "Homem vestindo camiseta branca", author: "Brian Lundquist" },
  calcas: { unsplashId: "fjFYb31Qsis", alt: "Homem usando calça cargo marrom", author: "Unsplash" },
  jaquetas: { unsplashId: "u-FOgI41dGQ", alt: "Homem de jaqueta corta-vento transparente", author: "David Beneš" },
} as const;
